name: CI_Dev

on:    
  push:
    branches:
      - Dev
    paths-ignore:
      - 'docs/**'


env: 
  MSG: Hello

jobs:
  build:
    runs-on: windows-latest
#    if: env.MSG == 'Hello'
    steps:
    - name: String matches
      if: env.MSG == 'Hello'
      run: echo String matches Hello

  test_docker:
    name: Test Docker
    runs-on: ubuntu-latest
    steps:
      - name: Show Docker version Pre
        run: |
          echo "**************************************************"
          docker-compose version
          echo "**************************************************"
          docker --version
          echo "**************************************************"
      - name: Update Docker version
        if: success()
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
          sudo sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
          sudo apt-get update
          sudo apt-get install lxc-docker
      - name: Show Docker version New
        if: success()
        run: |
          echo "**************************************************"
          docker-compose version
          echo "**************************************************"
          docker --version
          echo "**************************************************"

  test_matrix:
    name: Test matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        TARGET: [x86_64-apple-darwin, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        exclude: 
        - os: macos-latest
          TARGET: armv7-unknown-linux-musleabihf
        - os: macos-latest
          TARGET: x86_64-unknown-linux-musl
        - os: ubuntu-latest
          TARGET: x86_64-apple-darwin
    steps:
    - name: Building [ ${{ matrix.os }}, ${{ matrix.TARGET }} ]
      run: echo "Building [ ${{ matrix.os }}, ${{ matrix.TARGET }} ]"
