# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: CI

on: 
  push:
    branches:
      - master  
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

  schedule:
    - cron: '0 15 * * *'

jobs:
  show_event:
    name: Show event info
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
      - name: Show event info as JSON
        run: |
          write-host "This run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"
        shell: powershell
        id: show_Activity

  update_branch:
    name: Update PR Branch
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
      - name: Update Branch
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
          script: |
            await github.pulls.updateBranch({owner: context.issue.owner, repo: context.issue.repo, pull_number: context.issue.number})
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Check file version
        run: echo ${{ github.sha }}
      
      - name: Test npm
        run: |
          cd package
          npm install
          npm version patch -m "Upgrade to %s for reasons"
          cat package.json
          npm publish
