# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: CI_Tags

on:    
  push:
    tags:
      - brightran-testclock-latest
    paths-ignore:
      - 'docs/**'

jobs:
  first_job:
    name: First Job
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show first job
        run: write-host "This is First Job."
        shell: powershell
        id: show_job01

  second_job:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show second job
        run: echo "This is Second Job."
        shell: bash
        id: show_job02
  
  check_xcode:
    name: Check Xcode
    if: github.event_name == 'pull_request'
    runs-on: macOS-latest
    steps:
      - name: Check Xcode version
        run: |
          /usr/bin/xcodebuild -version
      
      - name: Update Xcode version
        run: |
          sudo rm -rf /usr/bin/xcodebuild
          xcode-select --install
          
      - name: Check new Xcode version
        run: |
          /usr/bin/xcodebuild -version
