# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: CI_Dev

on:    
  push:
    branches:
      - Dev
    paths-ignore:
      - 'docs/**'

jobs:
  first_job:
    name: First Job
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show first job
        run: write-host "This is First Job."
        shell: powershell
        id: show_job01

  second_job:
    name: Second Job
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show second job
        run: echo "This is Second Job."
        shell: bash
        id: show_job02
      
      - name: Run Sleep
        run: |
          Get-Date
          Start-Sleep -s 60
          Get-Date
        shell: pwsh
        id: run_sleep
  
  docker_push:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
      - name: Test Docker Push
        run: |
          docker login docker.pkg.github.com -u BrightRan -p GITHUB_TOKEN
