# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: CI

on: 
  push: 
    branches: 
      - master
    tags-ignore: 
      - '*.*'
    paths-ignore:
      - 'docs/**'
      - 'TestClock/package.json'
      - 'TestClock/.npmrc'

  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'
      - 'TestClock/package.json'
      - 'TestClock/.npmrc'

  schedule:
    - cron: '0 15 * * *'

jobs:
  show_event:
    name: Show event info
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: self-hosted
    steps:
      - name: Show event info as JSON
        run: |
          write-host "This run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"
        shell: powershell
        id: show_Activity

      - name: Update Branch
        if: github.event_name == 'pull_request'
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
          script: |
            await github.pulls.updateBranch({owner: context.issue.owner, repo: context.issue.repo, pull_number: context.issue.number})

      - name: Checkout
        if: success()
        uses: actions/checkout@v1

      - name: Check file version
        if: success()
        run: echo ${{ github.sha }}
