# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: CI

on: 
  push: 
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  show_event:
    name: Show event info
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: [self-hosted, windows]
    steps:
      - name: Show event info as JSON
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          write-host "This workflow run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "==================================================================================="
          write-host "Runner info:"
          write-host "$env:RUNNER_CONTEXT"
          write-host "***********************************************************************************"

  job_for_pr:
    if: github.event_name == 'pull_request'
    name: Job for PR
    runs-on: [self-hosted, windows]
    steps:
      - name: Update PR Branch
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
          script: |
            await github.pulls.updateBranch({owner: context.issue.owner, repo: context.issue.repo, pull_number: context.issue.number})

      - name: Check ref and runner
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        if: success()
        run: |
          echo "********************************************************************************************"
          echo "The branch or tag ref that triggered the workflow run: ${{ github.ref }}"
          echo "The commit SHA that triggered the workflow run: ${{ github.sha }}"
          echo "The head_ref or source branch of the pull request in a workflow run: ${{ github.head_ref }}"
          echo "The base_ref or target branch of the pull request in a workflow run: ${{ github.base_ref }}"
          echo "============================================================================================"
          echo "Runner info:"
          echo "$env:RUNNER_CONTEXT"
          echo "********************************************************************************************"

      - name: Checkout
        if: success()
        uses: actions/checkout@v1

  job_for_push:
    if: github.event_name == 'push'
    name: Job for Push
    runs-on: [self-hosted, windows]
    steps:
      - name: Check ref and SHA
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "********************************************************************************************"
          echo "The branch or tag ref that triggered the workflow run: ${{ github.ref }}"
          echo "The commit SHA that triggered the workflow run: ${{ github.sha }}"
          echo "============================================================================================"
          echo "Runner info:"
          echo "$env:RUNNER_CONTEXT"
          echo "********************************************************************************************"

      - name: Checkout
        uses: actions/checkout@v1
