# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: CI

on: 
  push: 
    branches: 
      - master
    tags: 
      - '*buildRelease*'
    paths-ignore:
      - 'docs/**'

  pull_request:
    types: [opened, edited, reopened, synchronize, labeled]
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  show_event:
    name: Show event info
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
      - name: Show event info as JSON
        run: |
          write-host "This workflow run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"
        shell: powershell

#  update_pr_branch:
#    if: github.event_name == 'pull_request'
#    name: Update PR branch
#    runs-on: windows-latest
#    steps:
#      - name: Update Branch
#        uses: actions/github-script@0.2.0
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          shell: bash
#          script: |
#            await github.pulls.updateBranch({owner: context.issue.owner, repo: context.issue.repo, pull_number: context.issue.number})

  check_file_version:
    name: Check file version
    runs-on: self-hosted
    steps:
      - name: Check ref and SHA
        if: success()
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          echo "The branch or tag ref that triggered the workflow run: ${{ github.ref }}"
          echo "The commit SHA that triggered the workflow run: ${{ github.sha }}"

      - name: Check head_ref and base_ref for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "The head_ref or source branch of the pull request in a workflow run: ${{ github.head_ref }}"
          echo "The base_ref or target branch of the pull request in a workflow run: ${{ github.base_ref }}"

      - name: Checkout
        if: success()
        uses: actions/checkout@v1
        with:
          github.ref: refs/tags/2.0.2-buildRelease

  test_matrix:
    name: Test matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        TARGET: [x86_64-apple-darwin, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        exclude: 
        - os: macos-latest
          TARGET: armv7-unknown-linux-musleabihf
        - os: macos-latest
          TARGET: x86_64-unknown-linux-musl
        - os: ubuntu-latest
          TARGET: x86_64-apple-darwin
    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"
