# This is a Continuous Integration workflow #
# The triggers are push and pull_request    #

name: CI

on: 
  push: 
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  workflow_run_info:
    name: Information about the workflow run
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
      - name: Show Information
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo "***********************************************************************************"
          echo "$env:GITHUB_CONTEXT"
          echo "***********************************************************************************"

  build:
    name: Build
    env:
      UPDATE_PR_BRANCH: false
    runs-on: [self-hosted, windows]
    steps:
      - name: Update PR Branch
        if: github.event_name == 'pull_request' && env.UPDATE_PR_BRANCH == 'true'
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
          script: |
            await github.pulls.updateBranch({owner: context.issue.owner, repo: context.issue.repo, pull_number: context.issue.number})

      - name: Checkout
        if: success()
        uses: actions/checkout@v2

      - name: MSBuild
        working-directory: TestClock
        run: msbuild TestClock.csproj

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: drop
          path: TestClock/bin/Debug
