# This is a Continuous Integration workflow #
# The triggers are push and pull_request    #

name: CI

on: 
  push: 
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  workflow_run_info:
    name: Information about the workflow run
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: [self-hosted, windows]
    steps:
      - name: Show Information
        run: |
          write-host "This workflow run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"

  build:
    name: Build
    env:
      UPDATE_PR_BRANCH: false
    runs-on: windows-latest
    steps:
      - name: Update PR Branch
        if: github.event_name == 'pull_request' && env.UPDATE_PR_BRANCH == true
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
          script: |
            await github.pulls.updateBranch({owner: context.issue.owner, repo: context.issue.repo, pull_number: context.issue.number})

      - name: Checkout
        if: success()
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108

      - name: Build with dotnet
        run: dotnet build --configuration Release
