# This is a Continuous Integration workflow #
# The trigger is Labels                     #

name: Events

on:
  release:
    types: [published]

  schedule:
    - cron: '0 15 * * *'

  label:
    types: [created, deleted, edited]

  milestone:
    types: [created, opened, edited]

  issues:
    types: [opened, reopened, labeled]

  issue_comment:
    types: [created, edited]

jobs:
  job_01:
    if: contains(github.event.comment.html_url, '/pull/')
    name: Job 01
    runs-on: ubuntu-latest
    steps:
      - name: Run job 01
        run: echo "contains(github.event.comment.html_url, '/pull/') == true, run job 01"

  job_end:
    if: contains(github.event.comment.html_url, '/pull/') == false
    name: Job End
    runs-on: ubuntu-latest
    steps:
      - name: Run Job End
        run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped."
