# This is a Continuous Integration workflow #
# The trigger is Labels                     #

name: Events

on:
  release:
    types: [published]

  schedule:
    - cron: '0 15 * * *'

  label:
    types: [created, deleted, edited]

  milestone:
    types: [created, opened, edited]

  issues:
    types: [opened, reopened, labeled]

  issue_comment:
    types: [created, edited]

jobs:
  show_event:
    if: contains(github.event.comment.html_url, '/pull/')
    name: Show event info
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
      - name: Show event info as JSON
        run: |
          write-host "This workflow run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"
        shell: powershell

  end_job:
    if: contains(github.event.comment.html_url, '/pull/') == false
    name: End job
    runs-on: [ubuntu-latest]
    steps:
      - name: Keep workflow success
        run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped."
