# This is a Continuous Integration workflow #
# The trigger is Labels                     #

name: Events

on:
  push

  release:
    types: [published]

  schedule:
    - cron: '0 15 * * *'

  label:
    types: [created, deleted, edited]

  milestone:
    types: [created, opened, edited]

jobs:
  show_event:
    name: Show event info
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
      - name: Show event info as JSON
        run: |
          write-host "This workflow run is triggered by ${{ github.event_name }} ."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"
        shell: powershell
