# This is a Continuous Integration workflow #
# The trigger is pushes and PR              #

name: Milestone

on: 
  milestone:
    types: [created, opened, edited]

jobs:
  first_job:
    name: First Job
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      GITHUB_CONTEXT_EVENY_NAME: ${{ toJson(github.event_name) }}
      GITHUB_CONTEXT_EVENY_ACTION: ${{ toJson(github.event.action) }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show  Activity
        run: |
          write-host "This run is triggered by $env:GITHUB_CONTEXT_EVENY_NAME - $env:GITHUB_CONTEXT_EVENY_ACTION."
          write-host "***********************************************************************************"
          write-host "$env:GITHUB_CONTEXT"
          write-host "***********************************************************************************"
        shell: powershell
        id: show_Activity
