name: PR Cleanup
on:
  pull_request:
    types:
      - closed

jobs:
  test_pr_event:
    name: Test PR event
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: windows-latest
    steps:
    - name: Test PR Closed
      run: |
        write-host "This workflow run is triggered by ${{ github.event_name }} ."
        write-host "***********************************************************************************"
        write-host "$env:GITHUB_CONTEXT"
        write-host "***********************************************************************************"
      shell: powershell
