name: Test npm package
on: 
  push: 
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  test_npm:
    name: Test npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Publish npm package
        run: |
          cd TestClock
          npm login --registry=https://npm.pkg.github.com
          npm version patch -m "Upgrade to %s"
          npm publish
