name: Publish npm package
on: 
  push: 
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  test_npm:
    name: Test npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
