name: Test

on: 
  pull_request:
    branches: 
      - master

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Test cut command
        run: |
          echo $GITHUB_REF | cut -d'/' -f3-
