name: Test

on:
  push:

env:
  ENVS: ENV_01

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Deployment with ENV_01
        if: env.ENVS == 'ENV_01'
        run: |
          echo hello
        env:
          VAR_API_KEY: API_KEY_01

      - name: Run Deployment with ENV_02
        if: env.ENVS == 'ENV_02'
        run: |
          echo hello
        env:
          VAR_API_KEY: API_KEY_02
