name: Test

on: push

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"


      - name: Check git config
        run: |
          git config --local user.name
          git config --local user.email

      - name: Changes
        run: |
          echo "Create test.txt - 200210" > test.txt
          git add -a
          git commit -m "Create test.txt - 200210"
          git push
