name: Test

on:
  push:

env:
  pluginId: 'plugin-fn-xml-node'

jobs:
  test:
    name: Test environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables 01
        env:
          test_env_var: test02/${{ env.pluginId }}
        run: |
          echo "*******************************************"
          echo "pluginId = $pluginId"
          echo "test_env_var = $test_env_var"
          echo "*******************************************"

      - name: Print environment variables 02
        run: |
          echo "*******************************************"
          echo "pluginId = $pluginId"
          echo "test_env_var = $test_env_var"
          echo "*******************************************"
