name: Test

on:
  push:
    branches-ignore: 
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Show contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "****************************************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "****************************************************************************************************"
