name: Test

on: 
  release:
    types: [edited, deleted]

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Information about the workflow run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "***********************************************************************************"
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"
          echo "***********************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "***********************************************************************************"
