name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  install libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
