name: Test

on: 
  push:

jobs:
  TEST:
    if: contains('Hello Mona the', 'Ran') == true
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Information about the workflow run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "***********************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "***********************************************************************************"
