name: Test

on: 
  push:
    paths: 
      - '!.github/workflows/**'
      - '.github/workflows/Test.yml'

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
