name: Test upgrade Unit Test Framework

on: push

jobs:
  test:
    name: Test
    runs-on: [macos-latest]
    steps:
      - name: Lists all .NET Core Global Tools
        run: nunit --version
      
#      - name: Upgrade Unit Test Framework
#        run: dotnet tool update 
