name: Test environment variable with container/image

on: push

env:
  NODE_VERSION: node:12.13

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: ${{ env.NODE_VERSION }}
    steps:
      - name: Show Default environment variables
        run: |
          echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_REF = $GITHUB_REF"
