name: Test Docker container action
on: push
jobs:
  build:
    name: Build
    container: node:10.16-jessie
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
