name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Docker container action
        uses: BriRanActions/hello-world-docker-action@master

      - name: Check directory
        run: |
          ls -lah /home/runner/work/_temp/_github_home/.m2/repository
          cat /home/runner/work/_temp/_github_home/.m2/repository/test.txt

      - name: Copy files
        run: |
          cp -r /home/runner/work/_temp/_github_home/.m2 $HOME
          ls -lah $HOME/.m2/repository
          cat $HOME/.m2/repository/test.txt
          echo "======================================="
          ls -lah /home/runner/work/_temp/_github_home
          echo "======================================="
          rm -rf /home/runner/work/_temp/_github_home/.m2/
          ls -lah /home/runner/work/_temp/_github_home
