name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        id: publish_bintray
        run: |
          echo "publish_bintray"

      - name: Create file run_send_message.txt
        if: success()
        run: |
          echo 'run_send_message == true' > run_send_message.txt

      - name: Upload file run_send_message.txt
        uses: actions/upload-artifact@v1
        with:
          name: run_send_message
          path: run_send_message.txt

      - name: Zip files
        run: |
          echo "Zip files"

      - name: Upload to release
        run: |
          echo "Upload to release"

  send_message:
    needs: [test]
    name: Send message
    runs-on: ubuntu-latest
    steps:
      - name: Download file run_send_message.txt
        uses: actions/download-artifact@v1
        with:
          name: run_send_message

      - name: Read file run_send_message.txt
        run: |
          cat run_send_message/run_send_message.txt

      - name: Discord notification
        run: |
          echo "Discord notification"
          echo "${{ steps.set_output.outputs.run_send_message }}"
