name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: List branches
        shell: bash
        run: |
          echo "********************************************"
          echo "list both remote-tracking and local branches"
          git branch -a
          echo "********************************************"
          echo "list remote-tracking branches"
          git branch -r
          echo "********************************************"
          
