name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v2

      - name: Test mkdir test1/test1-1
        run: |
          mkdir -p -v test1/test1-1
          ls

      - name: Test mkdir test2/test2-1
        run: |
          mkdir -p -v ./test2/test2-1
          ls
