name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Run with Bash
        run: |
          echo "*********************************************************************"
          WMIC CPU Get DeviceID,NumberOfCores,NumberOfLogicalProcessors
          echo "*********************************************************************"
          WMIC CPU Get /Format:List
          echo "*********************************************************************"
