name: Test Gradle

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Gradle version
        run: |
          echo "**************************"
          echo "Current Gradle version is:"
          gradle --version
          echo "**************************"

      - name: Upgrade Gradle version
        run: |
          echo "********************************************************"
          echo "Upgrade Gradle version:"
          gradlew wrapper --gradle-version=7.0 --distribution-type=bin
          echo "********************************************************"

      - name: Check new Gradle version
        run: |
          echo "**************************"
          echo "The new Gradle version is:"
          gradle --version
          echo "**************************"
