name: Test

on: push

env:
  GITHUB_PAT: ${{ secrets.MY_PAT }}

jobs:
  test:
    name: Test
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - name: Test timeout
        timeout-minutes: 6
        shell: pwsh
        run: |
          echo "START"
          Start-Sleep -s 270
          echo "END"
