name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: docker:brightran/testdocker/docker-ubuntu:v1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
