name: Test

on: 
  release:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Information about the workflow run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "***********************************************************************************"
          Event name: ${{ github.event_name }}
          Event type: ${{ github.event.action }}
          echo "***********************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "***********************************************************************************"
