name: Test

on: push
env:
  CACHE_NAME: cache-image

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout BriRanActions/hello-world-docker-action
        uses: actions/checkout@v2
        with:
          repository: BriRanActions/hello-world-docker-action
          token: ${{ secrets.MY_PAT }}
          path: hello-world-docker-action

      - name: Check directory
        run: |
          echo "****************************************************************************"
          echo $GITHUB_WORKSPACE
          echo $PWD
          ls
          echo "****************************************************************************"
          cd ..
          echo $PWD
          ls
          echo "****************************************************************************"

#      - name: Test Cache
#        uses: actions/cache@v1
#        with:
#          path: hello-world-docker-action
#          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
