name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: node:10.16-jessie
      ports: 
        - 80
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Check run_id and run_number
        run: |
          echo "run_id = ${{ github.run_id }}"
          echo "run_number = ${{ github.run_number }}"
