name: Test

on:
  push:
    tags: 
      - '**'
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Show contexts
        run: |
          echo "****************************************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "****************************************************************************************************"
