name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Create file
        uses: BriRanActions/hello-world-docker-action@master

      - name: Check files
        run: |
          echo "Current working-directory is $PWD"
