name: Test matrix jobs
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        TARGET: [x86_64-apple-darwin, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        include: 
        - os: macos-latest
          TARGET: x86_64-apple-darwin
        exclude:
          - os: ubuntu-latest
            TARGET: x86_64-apple-darwin

    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"
