name: Test matrix

on: 
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test_matrix_job:
    name: Test matrix job

    #env:
      #DART_VER: ${{ matrix.dart-version }}
      #CODE_VER: ${{ matrix.code-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10]
        dart-version: [stable, dev]
        code-version: [stable, insiders]

    if: (github.ref == 'master' && 'dev' == ${{ matrix.dart-version }} && 'insiders' == ${{ matrix.code-version }}) || (github.ref != 'master' && 'dev' != ${{ matrix.dart-version }} && 'insiders' != ${{ matrix.code-version }})
    #if: (github.ref == 'master' && matrix.dart-version == 'dev' && matrix.code-version == 'insiders') || (github.ref != 'master' && matrix.dart-version != 'dev' && matrix.code-version != 'insiders')

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Print environment variables
        run: |
          echo "matrix.dart-version = ${{ matrix.dart-version }}"
          echo "matrix.code-version = ${{ matrix.code-version }}"
          echo "github.ref = ${{ github.ref }}"
