name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
#      - name: Checkout
#        uses: actions/checkout@v2

      - name: git clone
        run: git clone https://github.com/BrightRan/TestClock.git

      - name: Show changes between commits
        shell: bash
        run: |
          echo "**********************************************************************************"
          echo $PWD
          ls
          cd TestClock
          echo "**********************************************************************************"
          git diff ${{ github.event.before }} ${{ github.sha }}
          echo "**********************************************************************************"
