name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Run with Bash
        shell: bash
        run: |
          echo "**************************************************"
          git --version
          echo "**************************************************"

      - name: Set PATH
        run: |
          echo %PATH%
