name: Test

on:
  pull_request:
    types: [closed]

jobs:
  test:
    if: github.event.pull_request.merged == 'true'
    name: Test PR event
    runs-on: ubuntu-latest
    steps:
      - name: Information about the workflow run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "*****************************************************************************************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "*****************************************************************************************************************************************************"
