name: Test Push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HEROKU_APP_NAME: ${{ 'TestPush' }}

on:
  push:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to TestPush
      run: git push "https://BrightRan:$GITHUB_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git" Dev:master
