name: Test

on: 
  release:
    types: [published]

jobs:
  test:
    name: Test Release event
    runs-on: ubuntu-latest
    steps:
      - name: Get release details
        run: |
          echo "*************************************************************"
          echo "GITHUB_REF = $GITHUB_REF"
          echo "tag name is: ${GITHUB_REF##*/}"
          echo "branch name is: ${{ github.event.release.target_commitish }}"
          echo "*************************************************************"

