name: Test

on:
  push:

env:
  API_KEY_01: ${{ secrets.API_KEY_01 }}
  API_KEY_02: ${{ secrets.API_KEY_02 }}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include: 
          - os: ubuntu-latest
            api_key: ${{ env.API_KEY_01 }}
          - os: windows-latest
            api_key: ${{ env.API_KEY_02 }}
    steps:
      - name: Show contexts
        run: |
          echo hello
        env:
          VAR_API_KEY: ${{ matrix.api_key }}
