name: Test matrix jobs
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-latest]
        TARGET: [x86_64-apple-darwin, armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        exclude: 
        - os: ubuntu-latest
          TARGET: x86_64-apple-darwin

        - os: macos-latest
          TARGET: armv7-unknown-linux-musleabihf

        - os: macos-latest
          TARGET: x86_64-unknown-linux-musl

    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"
