name: Test

on: push

#env:
#  GITHUB_REF: ${{ github.ref }}
#  GITHUB_REF_NO_PREFIX: ${GITHUB_REF##*/}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Manipulate parameters
        shell: bash
        run: |
          echo "******************************************************************************"
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_REF_NO_PREFIX = ${GITHUB_REF##*/}"
          echo "******************************************************************************"
