name: Test

on: 
  check_suite:
    types: [completed]

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check repository
        run: |
          echo "Current repository is ${{ github.repository }}"
