name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup-dart
        uses: DanTup/gh-actions/setup-dart@master

      - name: Check PATH with cmd
        shell: cmd
        run: |
          echo %path%
          echo "=============================================="
          pub --help

      - name: Check PATH with powershell
        shell: powershell
        run: |
          echo $env:path
          echo "=============================================="
          pub --help

      - name: Check PATH with pwsh
        shell: pwsh
        run: |
          echo $env:path
          echo "=============================================="
          pub.bat --help

      - name: Check PATH with bash
        shell: bash
        run: |
          echo $PATH
          echo "=============================================="
          pub.bat --help

      - name: Build
        shell: bash
        run: |
          pub.bat get
          mkdir build
          dart2native bin/main.dart -v -o build/outputname
