name: Test Push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HEROKU_APP_NAME: ${{ 'TestClock' }}

on:
  push:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to TestPush
      run: git push "https://BrightRan:$GITHUB_TOKEN@github.com/BrightRan/$HEROKU_APP_NAME" Dev:new_backend
