name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Information about the currently running job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "************************************************************************************************"
          echo "$JOB_CONTEXT"
          echo "************************************************************************************************"

      - name: Some test commands
        run: |
          echo $PWD
          epwdcho

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check job status
        if: always()
        run: |
          echo "The status of the currently running job is ${{ job.status }}."
