name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      JOB_CONTEXT: ${{ toJson(job) }}
    steps:
      - name: Information about workflow run and current job
        run: |
          echo "************************************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "************************************************************************************************"
          echo "$JOB_CONTEXT"
          echo "************************************************************************************************"

      - name: Some test commands
        run: |
          echo $PWD

      - name: Check job status
        run: |
          echo "Current job status is ${{ job.status }}."
