name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        id: publish_bintray
        run: |
          echo "publish_bintray"

      - name: Create file run_send_message.txt
        run: |
          echo 'true' > run_send_message.txt

      - name: Upload file run_send_message.txt
        uses: actions/upload-artifact@v1
        with:
          name: pass_status
          path: run_send_message.txt

      - name: Zip files
        run: |
          echo "Zip files"
          zf

      - name: Upload to release
        run: |
          echo "Upload to release"

  send_message:
    needs: [test]
    if: always()
    name: Send message
    runs-on: ubuntu-latest
    steps:
      - name: Download file run_send_message.txt
        uses: actions/download-artifact@v1
        with:
          name: pass_status

      - name: Read file run_send_message.txt
        id: set_output
        run: |
          echo "*****************************************************************"
          cat pass_status/run_send_message.txt
          echo "*****************************************************************"
          varr=$(<pass_status/run_send_message.txt)
          echo $varr
          echo "*****************************************************************"
          echo "::set-output name=run_send_message::$(<pass_status/run_send_message.txt)"
          echo "*****************************************************************"

      - name: Discord notification
        if: steps.set_output.outputs.run_send_message == 'true'
        run: |
          echo "Discord notification"
          echo "${{ steps.set_output.outputs.run_send_message }}"
