name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Docker container action
        uses: BriRanActions/hello-world-docker-action@master

      - name: Check directory
        run: |
          ls -lah /home/runner/work/_temp/_github_home/.m2/repository
          cat /home/runner/work/_temp/_github_home/.m2/repository/test.txt

      - name: Move files
        run: |
          mv /home/runner/work/_temp/_github_home/.m2/repository $HOME/.m2/repository
          ls -lah $HOME/.m2/repository
          cat $HOME/.m2/repository/test.txt
