name: Test

on:
  push:

jobs:
  test:
    name: Test Docker container action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.6'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

  container_job:
    name: Test container job
    runs-on: ubuntu-latest
    container: 
      image: python:3.7.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
