name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install http-server
        run: |
          npm install http-server

      - name: test http server
        run: |
          nohup npx http-server 8000 &
          curl http://127.0.0.1:8000/
