name: Test

on: push

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          git config --global user.name
          git config --global user.email

      - name: Checkout
        uses: actions/checkout@v2
