name: Test

on: push

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Show contexts
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "****************************************************************************************************"
          $GITHUB_CONTEXT
          echo "****************************************************************************************************"
          $JOB_CONTEXT
          echo "****************************************************************************************************"
          
      - name: Show steps contexts
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
          echo "****************************************************************************************************"
          $STEPS_CONTEXT
          echo "****************************************************************************************************"
