name: Test Environment Variables

on: push

env:
  VER_01: 1.8.2
  VER_02: 1.9.0

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: $VER_01

      - name: Check version of ninja-build tool
        run: |
          echo "**************"
          echo "Ninja version:"
          ninja --version
          echo "**************"
