name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        id: publish_bintray
        run: |
          echo "publish_bintray"

      - name: Set output
        id: set_output
        if: success()
        run: |
          echo "::set-output name=run_send_message::true"

      - name: Zip files
        run: |
          echo "Zip files"

      - name: Upload to release
        run: |
          echo "Upload to release"

  send_message:
#    if: jobs.test.steps.set_output.outputs.run_send_message == 'true'
    name: Send message
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        run: |
          echo "Discord notification"
          echo "${{ jobs.test.steps.set_output.outputs.run_send_message }}"
