name: Trigger pipeline runs via workflow

on: push

env:
  AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Trigger via action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/TestNewFeature/PrimaryProj'
          azure-pipeline-name: 'TestClock'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}
