name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Test directory
        run: |
          echo "run mkdir -p $HOME/.m2/repository"
          mkdir -p $HOME/.m2/repository
          echo "********************************ls in #HOME********************************"
          echo $HOME
          ls -lah $HOME
          echo "******************************ls in $HOME/.m2******************************"
          ls -lah $HOME/.m2

      - name:  Test copy
        run: |
          cp TestClock/. $HOME/.m2/repository
          ls $HOME/.m2/repository/TestClock
