name: Check Contains Function for Array
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Information about the workflow run
        run: |
          echo "*******************************************************************************************"
          echo "The head_ref or source branch of the pull request in a workflow run: ${{ github.head_ref }}"
          echo "The base_ref or target branch of the pull request in a workflow run: ${{ github.base_ref }}"
          echo "==========================================================================================="
          echo "$env:GITHUB_CONTEXT"
          echo "*******************************************************************************************"
