name: Test

on: push

env:
  GITHUB_PAT: ${{ secrets.MY_PAT }}

jobs:
  test:
    name: Test timeout
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - name: STEP1
        timeout-minutes: 2
        run: |
          echo "START at Get-Date"
          Start-Sleep -s 100
          echo "END at Get-Date"
      - name: STEP2
        timeout-minutes: 6
        shell: pwsh
        run: |
          echo "START at Get-Date"
          Start-Sleep -s 270
          echo "END at Get-Date"
