name: Test

on:
  push:

env:
  pluginId: 'plugin-fn-xml-node'

jobs:
  test:
    name: Test environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        env:
          test-env-var: test02/${{ env.pluginId }}
        run: |
          echo "*******************************************"
          echo "pluginId = $pluginId"
          echo "test-env-var = $test-env-var"
          echo "*******************************************"
