name: Test matrix

on: 
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test_matrix:
    env:
      DART_VER: ${{ matrix.dart-version }}
      CODE_VER: ${{ matrix.code-version }}
    if: (github.ref == 'master' && DART_VER == 'dev' && CODE_VER == 'insiders') || (github.ref != 'master' && DART_VER != 'dev' && CODE_VER != 'insiders')
    name: Test matrix job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10]
        dart-version: [stable, dev]
        code-version: [stable, insiders]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
