name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Test directory
        run: |
          echo "****************************************************"
          echo $PWD
          ls
          echo "****************************************************"
          mkdir -p $HOME/.m2/repository
          echo $HOME
          ls $HOME
          echo "****************************************************"
