name: Test

on: push

env:
  COMMANDS: echo $PWD;ls;cd TestClock;echo $PWD;ls

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Manipulate parameters
        shell: bash
        run: |
          echo "******************************************************************************"
          $COMMANDS
          echo "******************************************************************************"
