name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Test directory
        run: |
          echo "run mkdir -p $HOME/.m2/repository"
          mkdir -p $HOME/.m2/repository
          echo "****************************************************"
          echo $HOME
          ls -lah $HOME
          echo "****************************************************"
          ls -lah $HOME/.m2
          echo "****************************************************"
