name: Test upgrade Unit Test Framework

on: push

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Lists all .NET Core Global Tools
        run: dotnet tool list
      
#      - name: Upgrade Unit Test Framework
#        run: dotnet tool update 
