name: Test

on: push

env:
  COMMANDS: |
    echo "line 01"
    echo "line 02"
    echo "line 03"
    echo "line 04"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Manipulate parameters
        shell: bash
        run: |
          echo "******************************************************************************"
          $COMMANDS | wc -l
          echo "******************************************************************************"
