name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        id: publish_bintray
        run: echo "Execute Publish (Bintray)"

      - name: Create file post_message.txt and write 'true' into it
        run: echo 'true' > post_message.txt

      - name: Upload file post_message.txt
        uses: actions/upload-artifact@v1
        with:
          name: pass_file
          path: post_message.txt

      - name: Zip files
        run: echo "Execute Zip files"

      - name: Upload to release
        run: echo "Execute Upload to release"

  send_message:
    needs: [test]
    if: always()
    name: Send message
    runs-on: ubuntu-latest
    steps:
      - name: Download file post_message.txt
        uses: actions/download-artifact@v1
        with:
          name: pass_file

      - name: Read file post_message.txt
        id: set_output
        run: echo "::set-output name=post_message::$(<pass_file/post_message.txt)"

      - name: Discord notification
        if: steps.set_output.outputs.post_message == 'true'
        run: |
          echo "Execute Discord notification"
