name: Test

on: push

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  test:
    name: Test
    runs-on: [self-hosted, windows]
    steps:
      - name: Test Bash shell
        shell: bash
        run: |
          echo "*****************************************************************************************************"
          npm -v
          echo "*****************************************************************************************************"
          npm -h
          echo "*****************************************************************************************************"
