name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Create file
        run: |
          mkdir -p first/second
          echo "test text" > first/second/test.txt
          cat first/second/test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: testArtifact
          path: /first/second/
