name: Test

on: push
env:
  MY_PAT: ${{ secrets.MY_PAT }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: brightran/testdocker/docker-ubuntu:v1
      options: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $MY_PAT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
