name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: MSBuild
        working-directory: TestClock
        run: msbuild TestClock.csproj

      - name: Cache
        uses: actions/cache@v1
        with:
          path: TestClock/bin/Debug
          key: ${{ runner.os }}-TestClock-cache-${{ hashFiles('TestClock/bin/**') }}

  CHECK_CACHE:
    name: Check cahce
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v1
        with:
          path: TestClock/bin/Debug
          key: ${{ runner.os }}-TestClock-cache-${{ hashFiles('TestClock/bin/**') }}
