name: Test

on: push

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check git config
        run: |
          git config user.name
          git config user.email
