name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test function hashFiles
        run: |
          mkdir -p -v first/second
          cd first/second
          echo "Test function hashFiles 01" > test.txt

  TEST_02:
    name: Test 02
    runs-on: ubuntu-latest
    steps:
      - name: Test function hashFiles
        run: |
          mkdir -p -v first/second
          cd first/second
          echo "Test function hashFiles 02" > test.txt
          
