name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show changes between commits
        shell: bash
        run: |
          echo $(<git diff)
