name: Test

on: push

env:
  COMMANDS: |
    echo $PWD\n
    ls\n
    cd TestClock\n
    echo $PWD\n
    ls

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Manipulate parameters
        shell: bash
        run: |
          $COMMANDS
