name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test http server
        run: |
          nohup http-server -a localhost -p 8000 -c-1 &
          curl http://127.0.0.1:8000/
