name: Test

on: push

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  test:
    name: Test matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Information about the workflow run
        run: |
          echo "*********************************************************************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "*********************************************************************************************************************************"
