name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup-dart
        uses: DanTup/gh-actions/setup-dart@master

      - name: Build
        shell: bash
        run: |
          pub get
          mkdir build
          dart2native bin/main.dart -v -o build/outputname
