name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Set PATH
        shell: bash
        run: git --version

#      - name: Set PATH
#        run: |
#          pathman /as "C:\Program Files\Git\usr\bin\"
#          pathman /rs "C:\Program Files\Git\bin\"
