name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: [self-hosted, windows]
    steps:
      - name: Create a new folder
        run: mkdir testDir
        working-directory: ./testDir

      - name: Checkout
        uses: actions/checkout@v1
