name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check open ports
        run: |
          netstat -na | find 4873
