name: Test Default environment variables

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Show Default environment variables
        run: |
          echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_REF = $GITHUB_REF"
