name: Test Docker container
on: push
jobs:
  build:
    name: Build
    container: node:10.16-jessie
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Check working directory
        run: echo "Current working directory is: $PWD"
