name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: [self-hosted, windows]
    steps:
      - name: check workspace
        run: |
          echo "github.workspace = ${{ github.workspace }}"

#      - name: Checkout
#        uses: actions/checkout@v1
