name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Show changes between commits
        shell: bash
        run: |
          echo $(git diff --name-only --diff-filter=AM ${GITHUB_REF##*/})
