name: Trigger pipeline runs via workflow

on: push

env:
  AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Trigger via action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/TestNewFeature/PrimaryProj'
          azure-pipeline-name: 'TestClock'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Trigger via API
        shell: pwsh
        run: |
          $definitionId = "8"
          $definitionName = "ShowDateTime"
          $pat = $env:AZURE_DEVOPS_PAT
          $apiUri = "https://dev.azure.com/TestNewFeature/PrimaryProj/_apis/build/builds?api-version=5.1"
          $body = "{
          	`"definition`": {
          		`"id`": $definitionId,
          		`"name`": `"$definitionName`"
          	}
          }"
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $pat)))
          $Result = Invoke-RestMethod -Uri $apiUri -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Body $body -Method POST
          
      - name: check GCC version
        run: gcc -v
