name: Test Docker container action
on: push
jobs:
  build:
    name: Build
    container: localhost:5000/ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
