name: Test skip jobs

on:    
  push:
    branches:
      - Dev
    paths-ignore:
      - 'docs/**'

jobs:   
  skip_job:
    name: Skip Job
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Skip run
        run: echo "This job will be skipped when the condition is not met."

  always_job:
    name: Always run job
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped."
