name: Test

on: push

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: git config
        run: |
          git config --local user.name "Bright Ran"
          git config --local user.email "ranmaoliang@outlook.com"


      - name: Check git config
        run: |
          git config --local user.name
          git config --local user.email
