name: Test

on: 
  push:

jobs:
  TEST:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup-dart
        uses: DanTup/gh-actions/setup-dart@master

      - name: Check PATH with cmd
        shell: cmd
        run: |
          echo %path%

      - name: Check PATH with pwsh
        run: |
          echo %path%

      - name: Check PATH with bash
        shell: bash
        run: |
          echo $PATH

      - name: Build
        shell: bash
        run: |
          flutter pub get
          mkdir build
          dart2native bin/main.dart -v -o build/outputname
