name: Test

on: 
  push:

jobs:
  TEST:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create directory and file
        run: |
          mkdir -p -v first/second
          cd first/second
          echo "Test function hashFiles" > test.txt

      - name: Test function hashFiles
        run: |
          echo ${{ hashFiles('first/second/**') }}

  TEST_02:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create directory and file
        shell: bash
        run: |
          mkdir -p -v first/second
          cd first/second
          echo "Test function hashFiles" > test.txt

      - name: Test function hashFiles
        shell: bash
        run: |
          echo ${{ hashFiles('first/second/**') }}
