name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: brightran/testdocker/docker-ubuntu:v1
      env:
        MY_PAT: ${{ secrets.MY_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
