name: Test

on: 
  check_run:
    types: [completed]

jobs:
  TEST:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Information about the workflow run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "****************************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "****************************************************************************************"
